### ISSUE TITLE
Allow Element to return its html source

### ISSUE THREAD

**Issue by herenowcoder** [HashNuke/hound#10]
Hi!

I think if there's possibility to trivially add getting the html source of an element from the webdriver backend.

I'm sure webdriver protocol allows it, because I use it quite heavily in Ruby/Watir scripts.

I have an interesting set of scenarios where it is needed, maybe I drop few words on it:

I don't quite use phantomjs/hound (or other binding, like watir) for testing of long webapp flows. I rather write scripts which automate stuff. Lots of scripts. And they need to be fast.

So my typical scenario is to run a "webdriver client" like my app using Hound or a Watir script, visit some app, generate a needed state in it and then process the results, which means - read lots of DOM elements. Usually there's no need of further conversation with the webapp at that stage. But getting lots of elements via webdriver is slow. Phantomjs - and it is a fastest of the webdriver backends as they say - gives back a single element of a not-so-big page at ca 150-200 ms. If I have to iterate through tens or hundreds of them, the whole script goes painfully slow, and it's meant to be interactive.

So what I do in Ruby/Watir is to get the current source of some DOM subtree containing the results I need - webdriver gives it back with the proper current state even if it was updated via ajax - then I feed it to Hpricot or similar and I have everything parsed in fractions of the time before - like 0.1s instead of half of a minute. That is what I need. I'd like to do it in Elixir/hound as well. :)

**Comment by HashNuke** [comment]
There's now `inner_html/1` and `inner_text/1` in master branch. I'll publish a new version in a few days.

**Comment by herenowcoder** [comment]
Wow cool. Thanks! :D
