### ISSUE TITLE
navigate_to url as a certain user?

### ISSUE THREAD

**Issue by dorothythurston** [HashNuke/hound#101]
@HashNuke I have seen in your own integration tests (https://github.com/HashNuke/mogo-chat/blob/108c611177363a04d278221aabc03dcd2b66597c/test/test_helper.exs#L91 for example) you sign in the user by using a method that fills out a form and signs in the user. I was wondering if there might be a way to add another function like the hound helper navigate_to but one that could take a user and store it in the hound session params? Something to the effect of navigate_to url as: user? Thanks very much!

**Comment by HashNuke** [comment]
@dorothythurston that would be mixing application concerns with the webdriver library. The webdriver API allows access to the cookie jar but Hound has no knowledge of how the application uses it to implement auth.
