### ISSUE TITLE
Find element when there are multiple matching elements

### ISSUE THREAD

**Issue by drapergeek** [HashNuke/hound#105]
I noticed that if you use `find_element` and there are multiple elements that match your query, it will still operate fine. This seems like it could introduce some bugs that would be hard to track down in testing. If you believe you're clicking on a link and find out that the test framework is clicking on another, it could be confusing.

Would you consider having the app raise or otherwise handle the situation where you use `find_element` but there are multiple elements matching? I'd be happy to start a PR for this if it's something you're interested in just didn't want to do the work if you disagree.

**Comment by tuvistavie** [comment]
I think the current behavior is the one to go with, but I agree we could have a helper,
or an option to make the call fail if there is more than a single element.
@HashNuke What do you think?

**Comment by HashNuke** [comment]
@tuvistavie agree.
@drapergeek if there were multiple elements then you would be using `find_all_elements` or `find_within_element` to be more specific. `find_element` action is a direct translation of the corresponding webdriver API call.
