### ISSUE TITLE
`in_browser_session` doesn't work properly when using `do`

### ISSUE THREAD

**Issue by msambarino** [HashNuke/hound#107]
Whenever `in_browser_session` is used with `do` (i.e. `in_browser_session "some_session" do ... end`), functions inside the `do` block will be executed in the current_session, not the specified session. Furthermore,  a `BadFunctionError` is always raised in the end. 

I believe this is because the functions inside the `do` block are evaluated before calling `in_browser_session` and so it receives the result of the `do` block as its parameter instead of the functions themselves.

An example to illustrate:

```sh
iex(1)> use Hound.Helpers
nil
iex(2)> change_session_to("session A") #will be the default session
"b2e814010ed31a312fd850a00b6cf5db"
iex(3)> change_session_to("session B")                             
"dbadb7ea57cf542985530a6169d50804"
iex(4)> Hound.Helpers.Session.current_session_id #currently in session B
"dbadb7ea57cf542985530a6169d50804"
iex(5)> navigate_to("http://elixir-lang.org")
nil
iex(6)> current_url #session B current url should be "http://elixir-lang.org"
"http://elixir-lang.org/"
iex(7)> in_browser_session "session A" do
...(7)>   navigate_to("http://github.com")
...(7)> end
** (BadFunctionError) expected a function, got: [do: nil]
    (hound) lib/hound/helpers/session.ex:44: Hound.Helpers.Session.in_browser_session/2
iex(7)> change_session_to("session A")
"b2e814010ed31a312fd850a00b6cf5db"
iex(8)> current_url # session A url should be http://github.com but will be data;,
"data:,"
iex(9)> change_session_to("session B")                                            
"dbadb7ea57cf542985530a6169d50804"
iex(10)> current_url # session B url should remain http://elixir-lang.org but will be http://github.com instead           
"https://github.com/"
```

I think the best approach is to make `in_browser_session` a macro, so the `do` block isn't evaluated until the session has changed, im willing to work on this and make a PR. 

Otherwise, `in_broswer_session` needs to be used with a function:

```elixir
in_browser_session "other_session", fn -> 
    navigate_to(http:example.com) 
end
```

so the docs should be updated to reflect the proper usage (current example in the docs uses `in_browser_session ... do ... end`)

**Comment by tuvistavie** [comment]
@msambarino Thank you for reporting!

As I said in #108,

> I have no strong opinion about using a function or do
> but to avoid making a breaking change let's keep
> the function for now and change the docs to reflect this.
