### ISSUE TITLE
Hound + Heroku

### ISSUE THREAD

**Issue by tzveeJ** [HashNuke/hound#112]
Hopefully this is the right place for this issue.

I am using Phoenix with Heroku. I tried to start a phantomJS webdriver within the same Heroku application, but was unable to get it running. (I did get both started simultaneously, but that was because I had PhantomJS running as a worker and it didn't appear to be able to receive any traffic.) Instead, I had to create a new Heroku application, where I added the Heroku PhantomJS buildpack (https://github.com/stomita/heroku-buildpack-phantomjs) and created a Procfile with the line: `web: phantomjs --webdriver=127.0.0.1:$PORT` in order to get the webdriver to start and bind to the proper port.

This will certainly cause performance problems if I'm looking to do anything substantial, so I may need to split my application into the Phoenix endpoint and the Hound web scraping application, which isn't very desirable and has security concerns as well.

Is there an easier way to achieve what I did that I don't know about?

**Comment by HashNuke** [comment]
@tzveeJ background workers

**Comment by HashNuke** [comment]
@tzveeJ Heroku background processes cannot be bound to a port to receive inbound requests. So you will have to run phantomjs as a separate app as the `web` process so that you can bind to `$PORT`.

From heroku's docs - https://devcenter.heroku.com/articles/dynos
> Worker and one-off dynos cannot receive inbound requests.

Closing this issue.
