### ISSUE TITLE
Error when compiling with Elixir 1.3

### ISSUE THREAD

**Issue by wende** [HashNuke/hound#117]
```
== Compilation error on file lib/hound/response_parsers/chrome_driver.ex ==
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:318: :erl_anno.set(:file, 'nofile', -1)
    (stdlib) erl_parse.yrl:1516: anonymous fn/3 in :erl_parse.map_anno/2
    (stdlib) erl_parse.yrl:1631: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1517: :erl_parse.map_anno/2
    (stdlib) erl_lint.erl:703: :erl_lint."-set_file/2-lc$^0/1-0-"/2
    (stdlib) erl_lint.erl:448: :erl_lint.exprs_opt/3
    (stdlib) erl_eval.erl:173: :erl_eval.check_command/2
```

**Comment by tuvistavie** [comment]
Hi @wende,
This should be fixed with 1.0.1, could you give it a try please ? :smile:

**Comment by wende** [comment]
Yeah. Updating fixed it. However I seem to have a lot of these errors in other libraries like ExMachina. What's the cause? Maybe if it was pointed out by someone it'd be easier to fix it around libraries

**Comment by HashNuke** [comment]
@wend Daniel (@tuvistavie) fixed it and posted some comments on this issue https://github.com/HashNuke/hound/issues/115. It is about usage of `quote`.

Closing this issue. But please do re-open if you have any more compilation errors.
