### ISSUE TITLE
File download

### ISSUE THREAD

**Issue by RobinClowers** [HashNuke/hound#121]
Is there a way to download files over http with hound? I poked around but didn't see any support for it.

**Comment by tuvistavie** [comment]
This is driver dependent, and we do not have any clean way to do it for now.
PhantomJS does not seem to [support this](https://github.com/ariya/phantomjs/issues/10052) yet.

In what context do you need to download a file?
It could be easier to guide you towards a solution or workaround if we have the whole picture.

**Comment by RobinClowers** [comment]
@tuvistavie Thanks for getting back to me. I was hoping to log into a website and download a file, I was able to use an http client and do a direct post to login and then use the session cookie to get the file. I still think it would be cool if hound supported this, but I get it's tricky being driver dependent.
