### ISSUE TITLE
Empty results using PhantomJS

### ISSUE THREAD

**Issue by dfalling** [HashNuke/hound#153]
Hi, I'm trying the standard config with the PhantomJS web driver.  A very basic test which attempts to scrape www.example.com isn't working for me:

```elixir
defmodule WebScraper do
  use Hound.Helpers

  def scrape_example do
    Hound.start_session
    navigate_to "www.example.com"
    result = 
      find_element(:tag, "html")
      |> inner_html
    Hound.end_session

    result
  end
end
```

```shell
iex(5)> WebScraper.scrape_example
"<head></head><body></body>"
```

If I try to target something more specific, such as an `h1` or `a` tag, it eventually times out with no results.  How do I go about troubleshooting this?  Thanks!

**Comment by shankardevy** [comment]
make sure that your `test.exs` starts your web server by setting

```
config :your_app, YourApp.Web.Endpoint,
  http: [port: 4001],
  server: true
```

**Comment by dfalling** [comment]
Hi @shankardevy, thanks for the response!  I'm actually not using Hound to scrape my own server, but to scrape other servers (which I know are valid and active.)  Is there anything I could have missed that would make Hound return so little data?

**Comment by tuvistavie** [comment]
I am not exactly sure why, but we do not seem to support omitting the scheme,
could you try changing `www.example.com` to `http://www.example.com` please?

**Comment by dfalling** [comment]
Adding the scheme doesn't have a noticeable effect for me.

Here's the phantomjs output:

```
[INFO  - 2017-05-08T11:55:01.291Z] Session [2a92f190-33e5-11e7-b783-b59f71bed02a] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2017-05-08T11:55:01.292Z] Session [2a92f190-33e5-11e7-b783-b59f71bed02a] - page.customHeaders:  - {}
[INFO  - 2017-05-08T11:55:01.292Z] Session [2a92f190-33e5-11e7-b783-b59f71bed02a] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"mac-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"},"phantomjs.page.settings.userAgent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"}
[INFO  - 2017-05-08T11:55:01.292Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 2a92f190-33e5-11e7-b783-b59f71bed02a
```

Thanks for the help!

**Comment by tuvistavie** [comment]
I could not reproduce with the same version of phantomjs.
Could you give this a try please?

https://github.com/tuvistavie/hound-tiny-example

I setup Docker to run both phantomjs and the example you gave, it outputs the HTML correctly for me.

**Comment by dfalling** [comment]
That worked for me as well.  And then I noticed I didn't write out my changes when I added the scheme to my code.  Ooof.  Thanks so much for the help!

**Comment by tuvistavie** [comment]
Great, thanks for the feedback! :smile:
