### ISSUE TITLE
firefox_profile option is ignored

### ISSUE THREAD

**Issue by arathunku** [HashNuke/hound#173]
Hi,

I'm trying to modify few firefox profile settings and it looks like it had been supported by https://github.com/HashNuke/hound/pull/94 but after metadata support landed, this option(`firefox_profile`) is now completly ignored and instead, hardcoded profile with ua agent is used( https://github.com/HashNuke/hound/blob/428403884dcb85e3103d5b4e94e35c5864b46c37/lib/hound/browser.ex#L20). There's no support for `additional_capabilities` (https://github.com/HashNuke/hound/blob/78bd8a08d786e75c1178927e2310b293f779c683/lib/hound/session.ex#L35).

I'll try to submit a PR fixing this.

**Comment by arathunku** [comment]
fixed via https://github.com/HashNuke/hound/pull/174

**Comment by tuvistavie** [comment]
I published a new patch version with your fix, thank you!

**Comment by arathunku** [comment]
Great, thank you!
