### ISSUE TITLE
Pass additional options to desiredCapabilities

### ISSUE THREAD

**Issue by BinaryMuse** [HashNuke/hound#18]
It would be useful to be able to pass additional options to `desiredCapabilities` when creating a session. For example, I currently have a fork of Hound where I [pass `chromeOptions` to the session](https://github.com/BinaryMuse/hound/commit/de6d9048fe8f916da357f7439f56aaaecefbfd26):

```diff
diff --git a/lib/hound/json_driver.ex b/lib/hound/json_driver.ex
index f13c03b..ec61070 100644
--- a/lib/hound/json_driver.ex
+++ b/lib/hound/json_driver.ex
@@ -42,7 +42,11 @@ defmodule Hound.JsonDriver do
         cssSelectorsEnabled: true,
         browserName: browser_name,
         nativeEvents: false,
-        platform: "ANY"
+        platform: "ANY",
+        chromeOptions: [
+          excludeSwitches: ["--ignore-certificate-errors"],
+          args: ["--app=http://example.com"]
+        ]
       ]
     ]
```

**Comment by HashNuke** [comment]
Thanks. I'll look into merging this into the next version this week. Just published a new version

**Comment by HashNuke** [comment]
Hello @BinaryMuse. @darksheik fixed it in his pull request. Closing this issue.
