### ISSUE TITLE
selenium hub configuration issue

### ISSUE THREAD

**Issue by svb70** [HashNuke/hound#184]
given config.exs contains,

`config :hound, driver: "chrome_driver", host: "http://localhost/wd/hub" , port: 32768`

when I execute NavigationTests.fetch_ip,
`defmodule NavigationTests do
    
    use Hound.Helpers

    def fetch_ip do
        Hound.start_session

        navigate_to "http://google.com"

        IO.inspect page_source()

        Hound.end_session
    end
end`

I receive error,
`iex(1)> NavigationTests.fetch_ip
** (exit) exited in: GenServer.call(Hound.SessionServer, {:change_session, #PID<0.179.0>, :default, []}, 60000)
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Webdriver call status code 404 for post request http://localhost/wd/hub:32768/session.
Check if webdriver server is running. Make sure it supports the feature being requested.

            (hound) lib/hound/request_utils.ex:50: Hound.RequestUtils.handle_response/3
            (hound) lib/hound/session_server.ex:99: Hound.SessionServer.create_session/2
            (hound) lib/hound/session_server.ex:78: Hound.SessionServer.handle_call/3
            (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:774: GenServer.call/3
    (portal) lib/portal/door_tests.ex:6: NavigationTests.fetch_ip/0
iex(1)>
23:09:28.909 [error] GenServer Hound.SessionServer terminating
** (RuntimeError) Webdriver call status code 404 for post request http://localhost/wd/hub:32768/session.
Check if webdriver server is running. Make sure it supports the feature being requested.

    (hound) lib/hound/request_utils.ex:50: Hound.RequestUtils.handle_response/3
    (hound) lib/hound/session_server.ex:99: Hound.SessionServer.create_session/2
    (hound) lib/hound/session_server.ex:78: Hound.SessionServer.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.179.0>): {:change_session, #PID<0.179.0>, :default, []}
State: %{}
Client #PID<0.179.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:771: GenServer.call/3
    (portal) lib/portal/door_tests.ex:6: NavigationTests.fetch_ip/0
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:239: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:219: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:200: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:178: IEx.Evaluator.eval/3

iex(1)>`

The hub uri is formed as http://localhost/wd/hub:32768/session, which is incorrect. How would I configure hound to use correct hub uri? it should be http://localhost:32768/wd/hub

**Comment by tuvistavie** [comment]
This is a bug. We should probably change`host` to be only `localhost`, but that would break backward compatibility so let's support prefix paths in `host` for now.

**Comment by tuvistavie** [comment]
Sorry, after double checking I realized that the case was already handled.
The configuration should be:

```elixir
config :hound,
  driver: "chrome_driver",
  host: "http://localhost",
  port: 32768,
  path_prefix: "wd/hub/"
```

Please let me know if this works for you.

**Comment by svb70** [comment]
that works great. thanks!
