### ISSUE TITLE
Error when using find_element() in Firefox

### ISSUE THREAD

**Issue by GregoryCBT** [HashNuke/hound#213]
Getting an error whenever I try and run the find_element() function in my tests. All of these tests work fine in Chrome, but once I run them in Firefox they always fail at the first find_element(). This happens regardless of what selector I'm using to find the element. This is the error that gets displayed when the issue happens: 

`** (Hound.Error) could not get element {:name, "login"}: %{"element-6066-11e4-a52e-4f735466cecf" => "2dc74ae9-b3db-0c40-8853-c9930abf7439"}`

**Comment by feymartynov** [comment]
Same for me.

macos 10.13.5
selenium-server-standalone 3.11.0 from homebrew
firefox 60.0.1
hound 1.0.4
