### ISSUE TITLE
republish on Hex

### ISSUE THREAD

**Issue by herenowcoder** [HashNuke/hound#22]
Hi HashNuke!

I reproduced the problems w/ `:ibrowse` described [in this issue](https://github.com/HashNuke/hound/issues/19)

Now it's great you committed [a change](https://github.com/HashNuke/hound/commit/2c5cf4c026) fixing this, but you must've messed with Hex - the 0.5.9 package published on Hex doesn't have this commit.. so again we need to use Hound via Github ref in our deps, which screws things a bit.

Please republish package on Hex and keep it in sync with your tags.

Also note that you can overwrite the same ver of the Hex package only during 1 hour after publishing, so now you'll need to make it 0.5.10 or sth.

Cheers :]

herenowcoder

**Comment by HashNuke** [comment]
Too late but done. So closing this now :)
Thanks @herenowcoder ~!
