### ISSUE TITLE
"catch" should always come after "rescue" in try [Question]

### ISSUE THREAD

**Issue by JohnKacz** [HashNuke/hound#228]
Not a big issue and simple to fix, but I wanted to create an issue partly to better understand why both `catch` and `rescue` are needed. I'm assuming because `send_req/4` can "fail" in a lot of different ways?

Compiling gives a warning 
````
==> hound
Compiling 16 files (.ex)
warning: "catch" should always come after "rescue" in try
  lib/hound/request_utils.ex:9
````
https://github.com/HashNuke/hound/blob/0613a33f065a1eaa91fab602b8bc9af367d78ec1/lib/hound/request_utils.ex#L9-L18

Elixir 1.7.4

**Comment by danhper** [comment]
Thanks for reporting. This should be fixed in the latest version.
