### ISSUE TITLE
Fix broken source links from hexdocs

### ISSUE THREAD

**Issue by nietaki** [HashNuke/hound#231]
Currently the docs generate links based on a specific version/tag of the source, instead of `master`. 

For example https://hexdocs.pm/hound/Hound.Helpers.Element.html#inner_text/1 links to https://github.com/HashNuke/hound/blob/1.0.4/lib/hound/helpers/element.ex#L31

The problem with that is, the recent releases either aren't tagged, or are tagged with `vx.x.x` instead of just `x.x.x`.

One solution would be to  remove `source_ref: "#{@version}"` [in mix.exs](https://github.com/HashNuke/hound/blob/master/mix.exs#L14) and make another release.

Another solution would be to add the missing tags and make adding them part of the release process.

I'd be happy to do it the latter way myself, but it would require push permissions to this repo, it might be easier if one of the maintainers does it.

**Comment by danhper** [comment]
Thanks for catching this. This should now be fixed for the latest release.
