### ISSUE TITLE
release a new version? is this package still maintained?

### ISSUE THREAD

**Issue by krystofbe** [HashNuke/hound#234]
The latest version on hex.pm is `1.0.4 August 7, 2017 `
https://hex.pm/packages/hound

Would you release a new version containing all new changes on the `master` branch?

**Comment by danhper** [comment]
Sorry for the delay.
I indeed did not have time to maintain this for a while now.
Very sorry for the trouble.
I will wait to merge the latest PR and release a new version.

**Comment by danhper** [comment]
Just released version 1.1.0
