### ISSUE TITLE
(RuntimeError) invalid session id when running on alpine

### ISSUE THREAD

**Issue by edwinthinks** [HashNuke/hound#239]
Hello,

I'am attempting to install chromedriver for hound e2e tests on top of https://github.com/bitwalker/alpine-elixir-phoenix by adding:
```
RUN apk --no-cache --update add chromium chromium-chromedriver
```

However, I'am getting this error when trying to run this in CI.

```
$ chromedriver &
$ mix test
Starting ChromeDriver 72.0.3626.121 on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Compiling 16 files (.ex)
Generated you_must_goto app
..

  1) test home page has correct title (HoundTest)
     test/you_must_goto_web/e2e/hound_test.exs:8
     ** (RuntimeError) invalid session id
       (Driver info: chromedriver=72.0.3626.121,platform=Linux 4.19.23-coreos-r1 x86_64)
     code: navigate_to("/")
     stacktrace:
       (hound) lib/hound/request_utils.ex:52: Hound.RequestUtils.handle_response/3
       test/you_must_goto_web/e2e/hound_test.exs:9: (test)
```

I'am not entirely sure what this means or what the issue could be.

Thanks! Any assistance would be greatly appreciated!

**Comment by mimimalizam** [comment]
Hi @edwinthinks,

I experienced the same error locally in earlier today and installing google-chrome-stable helped in my case. Thought to share it in case it might help someone else. (I use Vagrant with Ubuntu 18).

**Comment by pdgonzalez872** [comment]
Having a similar issue, macOS Mojave.

@edwinthinks have you solved this?

@mimimalizam. How did you install `google-chrome-stable`? Any difference in the workflow? If so, could you please post them here?

Thank you!

**Comment by edwinthinks** [comment]
@pdgonzalez872 hey there; I didn't end up getting any solution :( I haven't had much time with using hound lately and left it as is. Hope you find a solution :)!

**Comment by formido** [comment]
You may want to load hound as a local dependency and put some `IO.puts` on the requests and responses. I was getting the same error message as you, and when hound made a call to `http://localhost:9515/session` the result was:

```
{"sessionId":"d6187f3aee07899a2f7773ffcd967ff6","status":33,"value":{"message":"session not created: This version of ChromeDriver only supports Chrome version 77\n  (Driver info: chromedriver=77.0.3865.10 (bc3579f611bbc73331171afe020ec7a45e6ccc55-refs/branch-heads/3865@{#93}),platform=Linu\
x 3.13.0-24-generic x86_64)"}}
```

I didn't investigate further, but you can see that there's a `sessionId` that hound probably tries to use again, but according to the embedded message it's not valid.

Would love to see this error surfaced cos I just spent 3 hours tracking it down. 💯 

It makes me think that libraries that wrap http apis should have a simple debug toggle so you can see all requests and responses, cos something in those usually seems to be the problem. Maybe they do and I just missed it.

Love that hound exists, it's crucial! 🥇

**Comment by pdgonzalez872** [comment]
Turns out that you need the version of Chrome to be the same as the version of Chromedriver. That solved our problem.

**Comment by pdgonzalez872** [comment]
Can we close this issue @edwinthinks?

**Comment by edwinthinks** [comment]
@pdgonzalez872 sure although I haven't been actively working with hound. If its reported working I can close this and only reopen if there is still an issue. Thanks @pdgonzalez872 !

**Comment by Sebisnow** [comment]
I have the same problem collecting performance metrics from a company-internal website.
I do not have the problem with the first session, that works perfectly, but if I try to asynchronously start another session I get the following error and both sessions crash (Browser windows open and the first session already navigated to the website):

```elixir
13:13:25.005 [error] Task #PID<0.274.0> started from #PID<0.269.0> terminating
** (RuntimeError) invalid session id
    (hound) lib/hound/request_utils.ex:52: Hound.RequestUtils.handle_response/3
    (hound_playground) lib/hound_playground.ex:56: HoundPlayground.collect_performance_metrics/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.22341430/0 in HoundPlayground.async_pisa_test/2>
```
Both chromedriver and chromium have the same version: 

```bash
sc1se@VM-65220044-Linux:~$ chromium-browser --version
  Chromium 77.0.3865.90 Built on Ubuntu , running on Ubuntu 18.04
sc1se@VM-65220044-Linux:~$ chromedriver --version
  ChromeDriver 77.0.3865.90 (58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830})
```

I initialize each session with the following:
```elixir
@chrome_prefs %{"protocol_handler" => %{"excluded_schemes" => %{"psadims" => false}}}

def start_new_session() do
    args =
    if System.get_env("browser") == "headless" do
      ["user-data-dir=/home/sc1se/.chromedriver", "headless"]
    else
      ["user-data-dir=/home/sc1se/.chromedriver"]
    end

    Hound.start_session(
      metadata: %{pid: self(), safe: false},
      driver: %{
        chromeOptions: %{
          "args" => args,
          "prefs" => @chrome_prefs
        }
      },
      browser: "chrome_driver"
    )
  end
```

The error also occurred when I used google-chrome (same major-, minor- and patch-version, only the build was a different one) instead of chromium.
Therefore this error is not only due to version differences in chromedriver and chrome. Any ideas why I get an invalid id error?

**Comment by linomp** [comment]
> 
> 
> Turns out that you need the version of Chrome to be the same as the version of Chromedriver. That solved our problem.

Confirmed, same here.   Windows 10.
