### ISSUE TITLE
CLI arguments

### ISSUE THREAD

**Issue by asconix** [HashNuke/hound#25]
It would be great to have an opportunity to define CLI arguments (e.g. proxy data) in hound. http://phantomjs.org/api/command-line.html. AFAIK you already coded this part but didn't push it yet, right?

**Comment by asconix** [comment]
Any chances to get CLI arguments into hound?

**Comment by HashNuke** [comment]
Just published a new version. I'll look into this for the next version this week.

**Comment by HashNuke** [comment]
@asconix phantomjs auto-starting has been removed to avoid patching and managing an external command/process. So closing this issue.
