### ISSUE TITLE
Response from phantomjs isn't processed properly

### ISSUE THREAD

**Issue by sevenseacat** [HashNuke/hound#34]
Testing from the `refactor` branch. 

The problem is the initial response from `:find_or_create_session`. As it is, I get the following error:

```
  1) test Users can create new projects (CreateProject)
     test/features/create_project_test.exs:7
     ** (exit) exited in: :gen_server.call(Hound.SessionServer, {:find_or_create_session, #PID<0.346.0>}, 60000)
         ** (EXIT) an exception was raised:
             ** (Poison.SyntaxError) Unexpected end of input
                 (poison) lib/poison/parser.ex:54: Poison.Parser.parse!/2
                 (poison) lib/poison.ex:83: Poison.decode!/2
                 (hound) lib/hound/response_parsers/phantom_js.ex:5: Hound.ResponseParsers.PhantomJs.parse/3
                 (hound) lib/hound/request_utils.ex:50: Hound.RequestUtils.send_req/4
                 (hound) lib/hound/session_server.ex:22: Hound.SessionServer.handle_call/3
                 (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
                 (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

With the test specified here: https://github.com/sevenseacat/ticketee-phoenix/blob/master/test/features/create_project_test.exs

After some debugging, it turns out that the params being passed to `Hound.ResponseParsers.PhantomJs.parse/3` are `"session", 303, ""`. Further up the call chain, the response from `{:ok, resp} = HTTPoison.post(url, body, headers)` is as follows:

```
pry(1)> resp
%HTTPoison.Response{body: "",
 headers: [{"Cache", "no-cache"},
  {"Content-Type", "application/json;charset=UTF-8"},
  {"Location",
   "http://localhost:8910/wd/hub/session/bff36540-0d12-11e5-af7d-d7e9deddf01f"}],
 status_code: 303}
```

It seems like the session ID is being returned as part of the location header, not as part of the content of the page to be parsed in the `parse/3` method. This was tested with both PhantomJs 1.8.2 and 2.0.0.

**Comment by HashNuke** [comment]
@sevenseacat Thanks. I'll look into it right away.

**Comment by HashNuke** [comment]
@sevenseacat I'm not able to reproduce the same error.

* I have the latest master of the project.
* I updated Hound to point to the latest version on refactor branch
* Installed phantomjs with `brew install phantomjs` and started it with "phantomjs -w"
* My phantomjs version is 2.0.0

```
★ phantomjs --version
2.0.0
```

Here's what I get when I run `mix test`:

```
★ mix test
.....

  1) test Users can create new projects (Ticketee.CreateProject)
     test/features/create_project_test.exs:7
     ** (RuntimeError) Unable to find element with link text 'New Project'
     stacktrace:
       (hound) lib/hound/response_parsers/phantom_js.ex:17: Hound.ResponseParsers.PhantomJs.parse/3
       (hound) lib/hound/request_utils.ex:50: Hound.RequestUtils.send_req/4
       (hound) lib/hound/helpers/page.ex:41: Hound.Helpers.Page.find_element/3
       test/features/create_project_test.exs:10
.

Finished in 8.5 seconds (0.2s on load, 8.3s on tests)
7 tests, 1 failures

Randomized with seed 42831
```

Can you push your latest master to github? I'll see if we have any differences

**Comment by HashNuke** [comment]
@sevenseacat also, I've been keeping watch on TravisCI builds. They seem to have been green for a while - https://travis-ci.org/HashNuke/hound/builds. The builds are configured to test on both selenium and phantomjs.
I'll publish a new version on Hex for now. But do let me know if this bug persists for you and I'll fix it.

**Comment by sevenseacat** [comment]
Yeah okay I must have forgotten to recompile something or something silly like that - I've just tried replicating it and it works now -_- Apologies for wasting your time, and I'm so glad this gem exists so I can get my testing on!

**Comment by HashNuke** [comment]
@sevenseacat No worries. Thanks for reporting anyway. I merged changes into master.
I'll publish in a few minutes. Just sorting out some TravisCI caching stuff to do one last build before publishing.
