### ISSUE TITLE
Within block

### ISSUE THREAD

**Issue by jontonsoup** [HashNuke/hound#38]
@HashNuke how do you feel about a `within` block? I've used it in the past where the page has the same text in several different places (like a chat conversation). 

http://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FSession%3Awithin

**Comment by jontonsoup** [comment]
@HashNuke whoops -- I meant a text matcher that can be scoped to a dom element.

**Comment by HashNuke** [comment]
@jontonsoup good idea ~!
:+1:

**Comment by jontonsoup** [comment]
I'm on it.

**Comment by jontonsoup** [comment]
https://github.com/HashNuke/hound/pull/41

**Comment by HashNuke** [comment]
Closing issue since PR has been merged.
