### ISSUE TITLE
Error when navigating to URL

### ISSUE THREAD

**Issue by nathanjohnson320** [HashNuke/hound#47]
Hi, 

Sometimes when I run the `navigate_to(url)` command I get the following error:

```
** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :timeout}}
    (hound) lib/hound/request_utils.ex:40: Hound.RequestUtils.send_req/4
    (arbiter) lib/runner.ex:55: anonymous fn/3 in Runner.run/1
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (arbiter) lib/runner.ex:54: Runner.run/1
    (arbiter) lib/runner.ex:26: Runner.handle_cast/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by HashNuke** [comment]
@nathanjohnson320 Can you paste the url if possible? Or can you check if the webserver that serves the request has a low speed or timeout?

**Comment by tomduncalf** [comment]
I too am having this issue intermittently. I can't provide an URL for the page in question as it requires login, but it is a forum page with quite a lot of YouTube iframe embeds, so I guess it is timing out waiting for the iframes to load - this is what it looks like from watching the browser (the browser is "Waiting for www.youtube.com" when the timeout occurs).

I've added `config :hound, http: [recv_timeout: :infinity]` to my `config.exs` but it doesn't fix the issue. I'm a total newcomer to Elixir so any help appreciated :) Seems like a great library otherwise!

**Comment by HashNuke** [comment]
@tomduncalf Looks like this is something to do with HTTPoison (a dependency). I'll talk to the author about it.

@nathanjohnson320 Sorry forgot about this. Just looking into it.

**Comment by HashNuke** [comment]
@nathanjohnson320 @tomduncalf Can you guys try with the latest version of HTTPoison (0.7.4) and hound (0.7.4)?

**Comment by nathanjohnson320** [comment]
Sure thing, I'll give it a shot after work :)

**Comment by HashNuke** [comment]
Looks like HTTPoison or hackney might be having a problem. #48 also looks related. I've filed an issue on the HTTPoison repo.

**Comment by tomduncalf** [comment]
Thanks @HashNuke (I assume you meant to reference #49?)!

**Comment by HashNuke** [comment]
@tomduncalf ah yes. It is #49. I just incremented the number and didnt realize PRs are counted too. Lazy me :)

**Comment by HashNuke** [comment]
There's a new version of hackney released yesterday. If HTTPoison is updated to use that I'm guessing this bug would go away (the changelog says body parsing is fixed).

**Comment by HashNuke** [comment]
Header handling was fixed in hackney. In v0.7.6, I've updated the dependency to the latest httpoison. The new release should fix this issue.
If you still have problems please do re-open this issue and let me know.
