### ISSUE TITLE
current_path function for phoenix testing?

### ISSUE THREAD

**Issue by praveenperera** [HashNuke/hound#51]
Hey I was doing some testing with Hound and realized that the current_url function doesn't work too well with phoenix route helpers. For example `assert current_url == post_path(conn, :new)` 

So I created a quick function using regex to get just the path instead of the full url:

``` elixir
def current_path do
  Regex.run(~r/(http[s]?:\/\/)?([^\/\s]+)(\/.*)/, current_url)
  |> Enum.at(3)
end
```

I was wondering if there's any plans of implementing a similar function. And if you are okay with the above solution I can post a PR, I've tested it and it works:

https://gist.github.com/praveenperera/83ef46f469d64190e016#file-navigation-ex

**Comment by HashNuke** [comment]
You need URI.parse/1 to get the path

**Comment by HashNuke** [comment]
@praveenperera about the PR yes. If you are interested, please do send a PR to add current_path.

**Comment by praveenperera** [comment]
Awesome did not know it was that easy (URI.parse), I send a PR soon
