### ISSUE TITLE
Timeouts when running multiple sessions

### ISSUE THREAD

**Issue by orikremer** [HashNuke/hound#55]
Hey,

I'm trying to visit multiple (11 in the example) pages and getting a timeout.
Running with 10 or less works fine.
(Testing with phantomjs).

Not sure if caused by hound or a dependent application or I'm missing a configuration.

Test to reproduce here:
https://gist.github.com/orikremer/0a3a2bcd4b9ef72f231a

Output:
```
WEBDRIVER=phantomjs mix test test/concurrent_sessions_test.exs
"Stopping Hound and restarting with options for test suite..."

17:14:24.278 [info]  Application hound exited: :stopped

17:14:29.577 [error] Task #PID<0.174.0> started from #PID<0.169.0> terminating
** (HTTPoison.Error) :timeout
    (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
    (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<3.57271661/0 in ConcurrentSessionsTest.test should be able to run multiple sessions concurrently/1>
    Args: []


  1) test should be able to run multiple sessions concurrently (ConcurrentSessionsTest)
     test/concurrent_sessions_test.exs:16
     ** (EXIT from #PID<0.169.0>) an exception was raised:
         ** (HTTPoison.Error) :timeout
             (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
             (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3



Finished in 5.2 seconds (0.1s on load, 5.1s on tests)
1 test, 1 failure
```

**Comment by HashNuke** [comment]
@orikremer Thanks for reporting. I'll test this out today.

**Comment by HashNuke** [comment]
@orikremer I just took a look at the code. I'm curious why you would want to test sessions concurrently? Can you explain what you are trying to test so that I can get some context?

**Comment by HashNuke** [comment]
@orikremer ah just remembered. Most webdrivers (I've know this about Phantomjs and Selenium+firefox have a limit on the number of sessions that they can simultaneously have at the same time. They'll freeze/crash/anything beyond that limit. https://groups.google.com/forum/#!topic/phantomjs/jwv7K4zmt7A

**Comment by orikremer** [comment]
@HashNuke Thanks. I have a large amount of web pages that I need to 'check' (visit and assert existence of elements) and I'm building a system to do it using hound.
I suspected that phantomjs may be the cause but wasn't able to confirm (aside from seeing it fail with > 10 sessions).
Code was structured to support multiple phantomjs processes (had to fork and support that in hound), although I was expecting more than 10 sessions per phantomjs.

**Comment by nelson687** [comment]
I'm doing exactly the same but getting a different error:
```
** (EXIT from #PID<0.204.0>) an exception was raised:
         ** (RuntimeError) could not find a session for process #PID<0.208.0>
             (hound) lib/hound/helpers/session.ex:114: Hound.Helpers.Session.current_session_id/0
             (hound) lib/hound/helpers/element.ex:159: Hound.Helpers.Element.attribute_value/2
             (crawlixir) lib/crawler.ex:54: Crawler.get_dates/1
             (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
