### ISSUE TITLE
Test absence of element?

### ISSUE THREAD

**Issue by backspace** [HashNuke/hound#56]
Hey, thanks for creating this library. I’m new to Elixir and happy to be able to test-drive my application.

One thing I’m accustomed to is being able to assert both the presence and absence of an element. For instance, if a user logs in as an admin, they should be able to see links to admin-only pages. I’d like to test for their absence when a non-admin logs in, but I can’t find anything like that.

Am I missing something? Is there some way to accomplish this you can suggest?

**Comment by HashNuke** [comment]
@backspace Matchers in Hound are very limited right now.

`find_all_elements/3` returns a list of elements if a selector matches. You could do the following:

`assert find_all_element(:css, "#foo") == []`

I'll add a matcher in a few days.

**Comment by backspace** [comment]
Ah, that’s a good enough workaround for now! Thanks for the quick response.

**Comment by HashNuke** [comment]
There's now an `element?` helper in the master branch. You'll find it here - https://github.com/HashNuke/hound/blob/master/lib/hound/matchers.ex#L39-L49

**Comment by backspace** [comment]
:tada:
