### ISSUE TITLE
change_session_to fails with Selenium + Chrome/Firefox

### ISSUE THREAD

**Issue by darksheik** [HashNuke/hound#59]
Hi!  Thanks for the great library.

Starting and stopping sessions this way works great, and I'm able to navigate to pages fine:
```
iex(1)> Hound.start_session
"a760dc48-b22f-44d5-b199-79a25e84cfaf"
iex(2)> Hound.end_session
:ok
```

I'm working with sessions for the first time, and when I try to use ```change_session_to```, it launches the browser properly but then dies in an apparent attempt to store the session ID in a HashDict.

I'm using Selenium, and the error occurs with both Chrome and Firefox sessions with the same behavior.

```
iex(4)> change_session_to :something
[error] GenServer Hound.SessionServer terminating
** (FunctionClauseError) no function clause matching in HashDict.put/3
    (elixir) lib/hash_dict.ex:40: HashDict.put(nil, :something, "7e3ae1ce-b2d0-462b-8334-dc523b9cac28")
    (hound) lib/hound/session_server.ex:60: Hound.SessionServer.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:change_session, #PID<0.302.0>, :something}
State: #HashDict<[]>
** (exit) exited in: :gen_server.call(Hound.SessionServer, {:change_session, #PID<0.302.0>, :something}, 30000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in HashDict.put/3
            (elixir) lib/hash_dict.ex:40: HashDict.put(nil, :something, "7e3ae1ce-b2d0-462b-8334-dc523b9cac28")
            (hound) lib/hound/session_server.ex:60: Hound.SessionServer.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (stdlib) gen_server.erl:212: :gen_server.call/3
```

Thanks!

**Comment by darksheik** [comment]
Update:  This occurs when I haven't already called ```Hound.start_session```.  If I do that first, I can then start a second with ```change_session_to```.  But what I'd really like to do is have each session completely encapsulated and not have to worry about my "base" session.

**Comment by HashNuke** [comment]
It's all about semantics. All sessions are assigned to the same process. They are just given different names. The default session is called "default". Since most us cases involves starting one browser session, the function has the word "change".

I'm open to suggestions with more details about code changes. Closing this issue for now.
