### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by ghost** [HashNuke/hound#63]
Such a minor thing but I was reading the docs and saw:
```
fill_field(element, input)
Sets a field’s value. The difference with input_info_field is that, the field is cleared before entering the new value
input_into_field(element, input)
Enters value into field
```

The first one refers to ``` input_info_field ``` which is meant to say ``` input_into_field ```

Obviously this isn't a huge issue but just making note of it :)

**Comment by HashNuke** [comment]
Hello @antmg83. Thank you for reporting this. That is certainly important. Would you like to send a pull request? I'll merge it right away.

**Comment by HashNuke** [comment]
Seems like this is already fixed in master.
