### ISSUE TITLE
Screenshot with (element) selector?

### ISSUE THREAD

**Issue by praneybehl** [HashNuke/hound#65]
Hi there,

Is it possible to take screenshots of DOM elements passing the element selector, pretty much like phantomjs - http://phantomjs.org/screen-capture.html ?

Cheers!

**Comment by darksheik** [comment]
@praneybehl I was able to achieve this using a combination of Hound full screenshot and command-line Imagemagick.  Hopefully this helps...

```
    temp_dir= System.tmp_dir()
    raw_filename = "#{temp_dir}#{session_id}-screenshot.png"
    target_filename = "#{temp_dir}#{session_id}-object.gif"

    element = Page.find_element(:id, "adcopy-puzzle-image-image")
    element_location = Element.element_location(element)
    element_size = Element.element_size(element)

    Hound.Helpers.Screenshot.take_screenshot(raw_filename)
    crop_options = "#{elem(element_size, 0)}x#{elem(element_size, 1)}+#{elem(element_location, 0)}+#{elem(element_location, 1)}"

    Logger.info "Attempting to create image: #{target_filename} with crop options #{crop_options}"

    System.cmd("convert", ["-crop", crop_options, "+repage", raw_filename, target_filename])
    System.cmd("rm", [raw_filename])
```

**Comment by praneybehl** [comment]
@darksheik thanks for the example mate. I was just wondering if there is an existing functionality. But maybe not. Also wondering if there is any scope to add such a functionality.

**Comment by HashNuke** [comment]
@praneybehl Hound only interacts with webdriver servers and exposes the common functionality that they expose as the webdriver API. The feature you mention isn't a part of the webdriver API. @darksheik's solution is very appropriate.
