### ISSUE TITLE
How to wait for an element to be visible

### ISSUE THREAD

**Issue by TFarla** [HashNuke/hound#66]
I am trying to test a React app and need to wait for React to be done loading before trying to fill in a form on the page. Is there a way to make the tests wait until an element is visible on the page before the continuing?

**Comment by darksheik** [comment]
@TFarla I had a similar need and wrote my own "retryer" based on the way Page.visible_on_page does it... a workaround for now.

```
defmodule MyApp.Retryer do
  import Hound.Helpers.Element
  @retry_time 1000

  def element_visible?(element, retries \\ 5) do
    if retries > 0 do
      case element_displayed?(element) do
        true -> true
        false ->
          :timer.sleep(@retry_time)
          element_visible?(element, retries - 1)
      end
    else
      element_displayed?(element)
    end
  end
end
```

Call with:

```
MyApp.Retryer.element_visible?({:id, "element_id"}, 10)
```

Where 10 is the number of times to retry.

**Comment by TFarla** [comment]
@darksheik Thank you!

**Comment by HashNuke** [comment]
All selectors have a retry argument as the last argument. The number of default retries is 5. You could just increase that to get the required functionality.

The default interval between retries can be changed via a config.
