### ISSUE TITLE
Page not fully rendering before `page_source()` is available

### ISSUE THREAD

**Issue by nathanhornby** [HashNuke/hound#74]
I'm having an issue where content on a page I'm accessing isn't populated when I start to interact with its dom. (it's actually inconstant, sometimes it is ready, sometimes it's not).

Is this something I need to deal with at the phantomjs end, or is there something hound can do to help here? I've looked through the docs and nothing has jumped out at me. I guess I need a kind of 'when the page has finished loading' condition.

Edit: `:timer.sleep(5000)` does the job for me, but it feels a bit dirty. Maybe this is the best approach though?

**Comment by darksheik** [comment]
Based on other retry schemes present in Hound, I came up with an idea of writing an "oscillator", wherein I can continually check for several different conditions which might be true before I proceed to do something.

```
defmodule MyApp.Retryer do
  @retry_time 1000

  def oscillate(function_list, retries \\ 60) do
    # Allows you to check multiple things that might be true at a given time
    results = Enum.map(function_list,
      fn x -> (try do x.() rescue _ -> false end)
    end)

    if retries > 0 do
      if Enum.any?(results) do
        results
      else
        :timer.sleep(@retry_time)
        oscillate(function_list, retries - 1)
      end
    else
      results
    end
  end
end
```

You would pass a list of functions into it like this:

```
results = Retryer.oscillate([
  fn() -> Text.visible_on_page?("Condition 1 visible text", 0) end,
  fn() -> Text.visible_on_page?("Condition 2 visible text", 0) end
])
```

It should return a list with a true in the position of the condition that ended up being true:

```
[true, false]
```

You can also use other things that are truthy like element finders:

```
results = Retryer.oscillate([
  fn() -> Page.find_element(:css, "#object1", 0) end,
  fn() -> Page.find_element(:css, "#object2", 0) end
])
```

Note: Always use 0 as the number of retries in your passed functions.

**Comment by nathanhornby** [comment]
That's really neat - thanks for sharing!

**Comment by tuvistavie** [comment]
I think this is the way to go.
I will close the issue for now, please reopen if you are still having some issues.
