### ISSUE TITLE
Raised exception when `navigate_to` results in a timeout

### ISSUE THREAD

**Issue by nathanhornby** [HashNuke/hound#75]
I'm wondering if this was an intentional approach that I need to deal with another way, or something that could benefit from some improvement (still learning).

But currently in cases of a timeout (etc.) when attempting a `navigate_to`, an exception is raised:

> ** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :timeout}}
>         (hound) lib/hound/request_utils.ex:43: Hound.RequestUtils.send_req/4

In my case I'd much rather be getting a status tuple back, like with the built-in `File` module. i.e.

```
{:error, :timout}
:ok
```

(Although ultimately in such cases I just want the `navigate_to` to be run again… so perhaps I'm looking at the problem the wrong way anyway).

Any recommended approach to such a problem? Or is it worth looking at adding a tuple response to that function?

**Comment by tuvistavie** [comment]
I think that you are right here, there are a few things that are currently raising exceptions but that should probably not.
I also need to handle this in a project I am currently working on, so I will try to send a PR with improved error handling when I find the time.
In the meanwhile, it's not very pretty but I suggest you simply rescue the error and retry a few times before failing.

**Comment by darksheik** [comment]
I've actually tried capturing this error in my app, but I think it doesn't allow me to because it's happening much deeper on the session GenServer in Hound than other simpler errors like can't find element.
