### ISSUE TITLE
Have more helpful errors

### ISSUE THREAD

**Issue by tuvistavie** [HashNuke/hound#79]
Right now, all failures result in a `RuntimeError`, which is ok for most cases,
but not very handful when we want to handle the errors, as we must pattern
match on the error message string.

In my particular use case, I use `find_element` on an element that is only present during
the page loading, to be sure that the page has fully loaded.
Therefore, the element not being present is the wanted state,
and I want to handle this particular error.

There are two approaches I can think of that could work nicely:

1. Raise `NoSuchElementError` or something similar for `find_element` and `find_within_element`

2. Return `{:ok, element}` or `{:error, the_error}` and add a `find_element!` function which would behave as the current function does.

The second approach would be more flexible in my opinion,
but is not backward compatible.

What do you think?

If you like the idea, I will be glad to send a PR.

**Comment by HashNuke** [comment]
@tuvistavie Yes. Let's make the change. Please do send a PR.

**Comment by tuvistavie** [comment]
@HashNuke Thanks for the fast reply. Do you want me to go with `{:ok, element}` and the bang function, or with a custom error?

**Comment by HashNuke** [comment]
@tuvistavie I would suggest the error. Because the return value of `find_element` needs to be pipe-able to the next helper function.

So `find_element` would return an element or `nil` and `find_element!` would raise an error if not found.

**Comment by tuvistavie** [comment]
@HashNuke Good point, let's go with this. I'll send a PR as soon as I'm done.

**Comment by HashNuke** [comment]
Closing since this has been fixed.
