### ISSUE TITLE
Drivers should be invoked from a facade API

### ISSUE THREAD

**Issue by josevalim** [HashNuke/hound#8]
Today, the Driver API is also the User API. This means drivers are required to be implement all user functions, even if the function implementation is going to be the same across all drivers. This leads to duplications.

For example, [the session functions](https://github.com/HashNuke/hound/blob/master/lib/hound/json_driver/session.ex#L16) are not specific to the driver, and even though, it would be required to be implemented by all drivers.

I believe instead the proper solution is to have a User API (maybe under `Hound.API` or `Hound.DSL`) which defines all the user functions which are implemented on top of the Driver API. This will be bring the following benefits:

1. It will avoid code duplication
2. The Driver API will be smaller, making it easier to create drivers
3. Since the Driver API is smaller, the Driver test suite can focus in smaller use cases
4. The documentation will be easier to maintain, as users only need to worry about the User API, and drivers won't need to duplicate the docs

Thanks for the great project!

**Comment by vitalis** [comment]
@HashNuke I think this issue can be closed
