### ISSUE TITLE
Can I open multiple tabs per session ?

### ISSUE THREAD

**Issue by andreijs** [HashNuke/hound#83]
Hey,

I am just wondering if I can open multiple tabs per session ?

Regards
Andrei

**Comment by HashNuke** [comment]
@andreijs that is currently not a part of webdriver specification. You'll have to open new sessions instead.

**Comment by HashNuke** [comment]
@andreijs My bad. It is supported in the spec. And Hound doesn't have the 2 window functions that are required to switch tabs. I'll implement that sometime next week.

**Comment by tuvistavie** [comment]
@andreijs Hi,

You cannot really work with multiple tabs. Well, if you really want to, you can try something like

```
with_keys [:control], do: send_text "t" # open new tab
with_keys [:alt], do: send_text "1" # focus tab 1
```

but it is OS and browser dependent, so it is clearly not a good idea.
However, you can work with multiple windows, and you can also be sure that all
links with `_target=blank` or `window.open` calls will open a new window and
not a new tab, so you do not need to worry about it.
Here is an example:

```
navigate_to "http://example.com"
execute_script("window.open('https://github.com')", []) # will open a new window
current_url # http://example.com
window_handles |> Enum.at(1) |> focus_window # will now focus the window opened with JS
current_url # https://github.com
close_current_window
window_handles |> Enum.at(0) |> focus_window # restore the focus on our original window
current_url # http://example.com
```

Note that I just added `focus_window` and `close_current_window`, so if you want to use
these please use the master branch until the next release.

Please feel free to reopen if something does not work for you.
