### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by vitalis** [HashNuke/hound#92]
Hi,
Any suggestions on testing file upload with hound?

**Comment by tuvistavie** [comment]
Using `fill_field` on a file input with the full path as a value should work, are you having any trouble with that?

**Comment by tuvistavie** [comment]
@vitalis Any news on this one?

**Comment by vitalis** [comment]
@tuvistavie no longer an issue :)

**Comment by jsteiner** [comment]
I got this error when trying to use `fill_field`:

```
** (RuntimeError) Element must be user-editable in order to clear it.
stacktrace:
  (hound) lib/hound/response_parsers/phantom_js.ex:17: Hound.ResponseParsers.PhantomJs.parse/3
  (hound) lib/hound/request_utils.ex:53: Hound.RequestUtils.send_req/4
  (hound) lib/hound/helpers/element.ex:72: Hound.Helpers.Element.fill_field/2
```

I did get it to work by writing a similar function (without the `clear_field`):

```elixir
  defp attach_file(element, input) do
    import Hound.RequestUtils
    element = get_element(element)
    session_id = Hound.current_session_id
    make_req(:post, "session/#{session_id}/element/#{element}/value", %{value: ["#{input}"]})
  end
```

If this seems reasonable, I should have time either this or next Friday to circle back with a PR.
