### ISSUE TITLE
Ability to make an API style POST while using Hound?

### ISSUE THREAD

**Issue by brainlid** [HashNuke/hound#95]
## Situation

There are 2 services ("Service A" and "Service B") that coordinate together to setup a Web session for a User on Service B. I'm testing Service B.

## Workflow

* Service A POSTs a request to service B (using API credentials) to setup a session for the User.
* Service B sets up temporary Redis tokens and provides Service A with a temporary one-time-use URL to send the User to on Service B
* Service A opens a new browser window/tab for the User that brings them to one-time-use URL in Service B
* Service B now handles the User's web requests for entering data, reviewing results, etc.
* When the User has completed their task, Service B redirects the User back to Service A to resume their operations there

## Problem

* Testing the Web interface without a handy tool like Hound is unpleasant
* When I start a hound_session, my attempts to make the API POST to setup the session are blocked
* Hound does not provide a way to do a custom (non-HTML initiated) "POST" action

Is there a way to either make my own POST outside of Hound that won't be blocked? Do you know of a better solution?

**Comment by brainlid** [comment]
After experimenting more with things like this...

```exlixir
    conn = api_v1_post(conn, ...)
    url = json_response(conn, 200)["url"]

    Hound.start_session
    try do
      navigate_to(url)
      take_screenshot("~/testing.png")
    after
      Hound.end_session
    end
```

I now believe the problem may not be with Hound, but my setup of phantomjs, selenium, etc. 

The error messages weren't clear to me.

```
     ** (exit) exited in: GenServer.call(Hound.SessionServer, {:change_session, #PID<0.314.0>, :default, %{}}, 60000)
         ** (EXIT) an exception was raised:
             ** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}}
                 (hound) lib/hound/request_utils.ex:43: Hound.RequestUtils.send_req/4
                 (hound) lib/hound/session_server.ex:67: Hound.SessionServer.handle_call/3
                 (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
                 (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

If the problem is my incorrect setup, I'd kindly suggest improving the error to be more instructive. :)

**Comment by brainlid** [comment]
Got it working now.

**Comment by tuvistavie** [comment]
@brainlid Hi,

> Hound does not provide a way to do a custom (non-HTML initiated) "POST" action

Hound really is browser automation, so this will not be a feature in the future either,
it should be dealt with a normal HTTP client.

> If the problem is my incorrect setup, I'd kindly suggest improving the error to be more instructive. :)

It is already improved in master :+1: 

Please let us know if you run in other issues, thank you! :smile:
